#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#
image: registry.stealthsoftwareinc.com/stealth/builder-images/ubuntu:22.04

build:
  stage: build
  before_script:
    - apt-get -q -y update
    - apt-get -q -y install python3-venv
    - mkdir tmp
    - python3 -m venv tmp/picozkenv
    - source ./tmp/picozkenv/bin/activate
    - python3 -m pip install setuptools pip --upgrade
  script:
    - python3 -m pip install .

test:
  stage: test
  before_script:
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.stealthsoftwareinc.com/stealth/wiztoolkit.git" tmp/wiztoolkit
    - make -C tmp/wiztoolkit deps
    - make -C tmp/wiztoolkit
    - make -C tmp/wiztoolkit install
    - apt-get -q -y update
    - apt-get -q -y install python3-venv
    - python3 -m venv tmp/picozkenv
    - source ./tmp/picozkenv/bin/activate
    - which python3
    - python3 -m pip install setuptools pip --upgrade
  script:
    - python3 -m pip install .[examples]
    - cd examples
    - wget https://media.githubusercontent.com/media/usnistgov/SDNist/main/nist%20diverse%20communities%20data%20excerpts/massachusetts/ma2019.csv
    - python3 run_tests.py
